# ╃
#  .▀▀█▀▀ .
#    :▓.:   ar <3
# . ▀▀ : ╃
# -=-=-=-=-=-=-=-=-=-=-=
# goal: Voxtype push-to-talk dictation + transcript (home-manager side).
# -=-=-=-=-=-=-=-=-=-=-=
# Packages come from ./shared.nix; this side keeps the HM-native bits:
# the voxtype config (xdg.configFile) and the two user services (systemd.user).
{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.usrset.dictation;
  shared = import ./shared.nix { inherit pkgs lib; };

  # Extra binaries voxtype needs at runtime (typing, clipboard, media pause, notif)
  runtimeBinPath = lib.makeBinPath [
    pkgs.voxtype
    pkgs.wtype
    pkgs.wl-clipboard
    pkgs.libnotify
    pkgs.playerctl
    pkgs.coreutils
    pkgs.bash
  ];
in
{

  config = lib.mkIf cfg.enable {
    home.packages = shared.packages; # end of home.packages

    xdg.configFile."voxtype/config.toml".text = ''
            # Voxtype - generated by nix-config (juajar/liijar/dictation)
            # Hold F9 to dictate; release to transcribe. Text types at the cursor.
            state_file = "auto"

            [hotkey]
            enabled = true
            key = "F9"

      [audio]
      device = "default"
            sample_rate = 16000
            max_duration_secs = 60
            pause_media = true

            [whisper]
            model = "base.en"
            language = "en"

            [output]
            mode = "type"
            fallback_to_clipboard = true
            type_delay_ms = 1

            [output.notification]
            on_transcription = true
    ''; # end of xdg.configFile.voxtype

    # download the whisper model once (skips if already present in ~/.local/share/voxtype/models)
    systemd.user.services.voxtype-model = {
      Unit = {
        Description = "Voxtype whisper model bootstrap";
        After = [ "graphical-session-pre.target" ];
      };
      Service = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStart = "${pkgs.bash}/bin/bash -lc 'test -e \"\${HOME}/.local/share/voxtype/models/ggml-base.en.bin\" || ${lib.getExe pkgs.voxtype} setup --download --no-post-install'";
      };
      Install.WantedBy = [ "default.target" ];
    }; # end of voxtype-model

    # the dictation daemon - starts on login, waits for the model bootstrap
    systemd.user.services.voxtype = {
      Unit = {
        Description = "Voxtype dictation daemon";
        After = [ "voxtype-model.service" ];
      };
      Service = {
        ExecStart = "${lib.getExe pkgs.voxtype}";
        Restart = "on-failure";
        RestartSec = 3;
        Environment = [ "PATH=${runtimeBinPath}:/run/current-system/sw/bin" ];
      };
      Install.WantedBy = [ "default.target" ];
    }; # end of voxtype
  }; # end of config
}
