# ╃
#  .▀▀█▀▀ .
#    :▓.:   ar <3
# . ▀▀ : ╃
# -=-=-=-=-=-=-=-=-=-=-=
# goal: Voxtype push-to-talk dictation + transcript.
# -=-=-=-=-=-=-=-=-=-=-=
{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.usrSettings.dictation;

  # Extra binaries voxtype needs at runtime (typing, clipboard, media pause, notif)
  runtimeBinPath = lib.makeBinPath [
    pkgs.voxtype
    pkgs.wtype
    pkgs.wl-clipboard
    pkgs.libnotify
    pkgs.playerctl
    pkgs.coreutils
    pkgs.bash
  ];
in
{
  options = {
    usrSettings.dictation.enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = "Enable push-to-talk dictation (voxtype) + meeting/VTT transcription";
    }; # end of dictation.enable
  }; # end of options

  config = lib.mkIf cfg.enable {
    home.packages = with pkgs; [
      voxtype # local voice-to-text daemon (Whisper engine)
      wtype # Wayland typing (needed for output.mode = "type")
      wl-clipboard # clipboard fallback output
      libnotify # transcription notifications
      playerctl # auto-pause MPRIS media while recording
      (pkgs.writeShellScriptBin "vtt" ''
        # vtt - voxtype meeting-mode transcriber (continuous -> VTT/SRT/Markdown export)
        # usage: vtt <start|stop|export|help>
        case "''${1:-}" in
          start)
            shift
            exec ${lib.getExe pkgs.voxtype} meeting start "$@"
            ;;
          stop)
            shift
            exec ${lib.getExe pkgs.voxtype} meeting stop "$@"
            ;;
          export)
            shift
            exec ${lib.getExe pkgs.voxtype} meeting export --format vtt "$@"
            ;;
          help | -h | --help)
            echo "vtt - voxtype meeting transcriber"
            echo "  vtt start              begin a continuous transcription session"
            echo "  vtt stop               finish transcribing"
            echo "  vtt export [path]      export the last meeting as a .vtt transcript"
            echo "  vtt <args...>          pass through to 'voxtype meeting <args...>'"
            ;;
          *)
            exec ${lib.getExe pkgs.voxtype} meeting "$@"
            ;;
        esac
      '')
    ]; # end of home.packages

    xdg.configFile."voxtype/config.toml".text = ''
            # Voxtype - generated by nix-config (modjar/usrbin/dictation)
            # Hold F9 to dictate; release to transcribe. Text types at the cursor.
            state_file = "auto"

            [hotkey]
            enabled = true
            key = "F9"

      [audio]
      device = "default"
            sample_rate = 16000
            max_duration_secs = 60
            pause_media = true

            [whisper]
            model = "base.en"
            language = "en"

            [output]
            mode = "type"
            fallback_to_clipboard = true
            type_delay_ms = 1

            [output.notification]
            on_transcription = true
    ''; # end of xdg.configFile.voxtype

    # download the whisper model once (skips if already present in ~/.local/share/voxtype/models)
    systemd.user.services.voxtype-model = {
      Unit = {
        Description = "Voxtype whisper model bootstrap";
        After = [ "graphical-session-pre.target" ];
      };
      Service = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStart = "${pkgs.bash}/bin/bash -lc 'test -e \"\${HOME}/.local/share/voxtype/models/ggml-base.en.bin\" || ${lib.getExe pkgs.voxtype} setup --download --no-post-install'";
      };
      Install.WantedBy = [ "default.target" ];
    }; # end of voxtype-model

    # the dictation daemon - starts on login, waits for the model bootstrap
    systemd.user.services.voxtype = {
      Unit = {
        Description = "Voxtype dictation daemon";
        After = [ "voxtype-model.service" ];
      };
      Service = {
        ExecStart = "${lib.getExe pkgs.voxtype}";
        Restart = "on-failure";
        RestartSec = 3;
        Environment = [ "PATH=${runtimeBinPath}:/run/current-system/sw/bin" ];
      };
      Install.WantedBy = [ "default.target" ];
    }; # end of voxtype
  }; # end of config
}
