#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════
#  testinstall.sh Tier 1 logic tests for nixinstall
#  NOTE: these tests are run by an AI/LLM during development.
#  They are NOT part of the installer and never ship in the ISO.
#  Run with:  ./resjar/nixbin/testinstall.sh  (stdin from /dev/null)
#
#  Covers: pick_part parsing (IFS regression), dedup, manual +
#  "None (skip)" paths, device placeholders, plan_partitions layout
#  invariants (rest-of-disk LAST), gen_base_config output (bootloader
#  per mode, user, hashed password, flakes, ssh block), prompt
#  validation retries, and full stubbed iso_install() runs through
#  every step (format -> mount -> identity -> core install -> clone).
# ═══════════════════════════════════════════════════════════════
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
TEST_DIR=$(mktemp -d)
trap 'rm -rf "$TEST_DIR"' EXIT

PASS=0
FAIL=0

pass() { PASS=$((PASS + 1)); printf '  PASS  %s\n' "$1"; }
fail() { FAIL=$((FAIL + 1)); printf '  FAIL  %s\n' "$1"; }
assert_eq() { # expected actual label
    if [ "$2" = "$1" ]; then
        pass "$3"
    else
        fail "$3 (expected '$1' got '$2')"
    fi
}
assert_contains() { # needle file label
    if grep -qF -- "$1" "$2" 2>/dev/null; then
        pass "$3"
    else
        fail "$3 (missing '$1' in $2)"
    fi
}
assert_not_contains() { # needle file label
    if grep -qF -- "$1" "$2" 2>/dev/null; then
        fail "$3 (found '$1' in $2)"
    else
        pass "$3"
    fi
}

# ──[build stub binaries]
STUB_BIN="$TEST_DIR/bin"
STUB_DIR="$TEST_DIR/stubs"
mkdir -p "$STUB_BIN" "$STUB_DIR"

cat > "$STUB_BIN/gum" <<'GUM'
#!/usr/bin/env bash
read_consume() { [ -s "$1" ] && { head -n1 "$1"; sed -i "1d" "$1"; }; }
case "$1" in
    choose)
        shift
        cat > "$STUB_DIR/last_options" 2>/dev/null || true
        read_consume "$STUB_DIR/choose"
        ;;
    confirm)
        ans=$(read_consume "$STUB_DIR/confirms")
        [ "$ans" = "1" ]
        ;;
    input)
        printf 'input %s\n' "$*" >> "$STUB_DIR/input_args"
        read_consume "$STUB_DIR/inputs"
        ;;
    spin)
        shift
        while [ "$1" != "--" ] && [ $# -gt 0 ]; do shift; done
        shift
        "$@" 2>&1
        exit $?
        ;;
    log)
        shift; shift
        printf 'LOG %s\n' "$*" >&2
        exit 0
        ;;
    *)
        exit 0
        ;;
esac
GUM
chmod +x "$STUB_BIN/gum"

cat > "$STUB_BIN/lsblk" <<'LSBLK'
#!/usr/bin/env bash
case "$*" in
    *-rno*) cat "$STUB_DIR/lsblk_parts" ;;
    *-ndo*) cat "$STUB_DIR/lsblk_disks" ;;
    *)      cat "$STUB_DIR/lsblk_display" ;;
esac
LSBLK
chmod +x "$STUB_BIN/lsblk"

cat > "$STUB_BIN/fzf" <<'FZF'
#!/usr/bin/env bash
read_consume() { [ -s "$1" ] && { head -n1 "$1"; sed -i "1d" "$1"; }; }
cat > "$STUB_DIR/last_fzf" 2>/dev/null || true
read_consume "$STUB_DIR/fzf"
FZF
chmod +x "$STUB_BIN/fzf"

cat > "$STUB_BIN/git" <<'GIT'
#!/usr/bin/env bash
case "$1" in
  clone)
    url="$2"; dir="$3"
    mkdir -p "$dir"
    printf '{ }\n' > "$dir/flake.nix"
    printf 'git clone %s %s\n' "$url" "$dir" > "$STUB_DIR/git.log"
    ;;
  *)
    exit 0
    ;;
esac
GIT
chmod +x "$STUB_BIN/git"

cat > "$STUB_BIN/nixos-install" <<'NI'
#!/usr/bin/env bash
if [ -n "${NIXOS_INSTALL_FAIL:-}" ]; then
    printf 'nixos-install FAILED (simulated)\n' >&2
    exit 1
fi
printf 'nixos-install %s [NIX_CONFIG=%s]\n' "$*" "${NIX_CONFIG:-}" > "$STUB_DIR/nixos_install.log"
exit 0
NI
chmod +x "$STUB_BIN/nixos-install"

cat > "$STUB_BIN/nixos-generate-config" <<'NGC'
#!/usr/bin/env bash
root=""
prev=""
for a in "$@"; do
    [ "$prev" = "--root" ] && root="$a"
    prev="$a"
done
root="${root:-/mnt}"
mkdir -p "$root/etc/nixos"
cat > "$root/etc/nixos/hardware-configuration.nix" <<'HW'
# hardware-configuration stub (generated by testinstall.sh)
{ ... }: {
  fileSystems."/" = { device = "/dev/vda2"; fsType = "ext4"; };
}
HW
printf 'nixos-generate-config --root %s\n' "$root" > "$STUB_DIR/genconfig.log"
exit 0
NGC
chmod +x "$STUB_BIN/nixos-generate-config"

cat > "$STUB_BIN/nixos-enter" <<'NE'
#!/usr/bin/env bash
# no output: uid:gid resolution falls back to the warn path
exit 0
NE
chmod +x "$STUB_BIN/nixos-enter"

cat > "$STUB_BIN/sudo" <<'SUDO'
#!/usr/bin/env bash
# Deny-list: these MUST never run on the host during a test, even if a
# flow reaches them. Everything else is passed through ONLY because it is
# already shadowed by a no-op/fixture stub earlier in the test PATH.
deny=' reboot poweroff shutdown halt cfdisk fdisk sfdisk parted dd rm mv rmdir '
first="$1"
[ -z "$first" ] && exit 0
if case "$deny" in *" $first "*) true ;; *) false ;; esac; then
    printf 'BLOCKED: sudo %s\n' "$*" >> "$STUB_DIR/sudo.log"
    printf 'BLOCKED: sudo %s\n' "$*" >&2
    exit 1
fi
"$@"
SUDO
chmod +x "$STUB_BIN/sudo"

# mkfs stubs log their calls so tests can verify which filesystem was formatted where
for c in mkfs.fat mkfs.ext4 mkfs.btrfs mkfs.xfs; do
    printf '#!/usr/bin/env bash\necho "%s $*" >> "$STUB_DIR/mkfs.log"\nexit 0\n' "$c" > "$STUB_BIN/$c"
    chmod +x "$STUB_BIN/$c"
done

# mount-family stubs log into mount.log (prefixed by command name)
for c in mount umount swapon; do
    printf '#!/usr/bin/env bash\necho "%s $*" >> "$STUB_DIR/mount.log"\nexit 0\n' "$c" > "$STUB_BIN/$c"
    chmod +x "$STUB_BIN/$c"
done
printf '#!/usr/bin/env bash\necho "mkswap $*" >> "$STUB_DIR/mkfs.log"\nexit 0\n' > "$STUB_BIN/mkswap"
chmod +x "$STUB_BIN/mkswap"
printf '#!/usr/bin/env bash\necho "btrfs $*" >> "$STUB_DIR/btrfs.log"\nexit 0\n' > "$STUB_BIN/btrfs"
chmod +x "$STUB_BIN/btrfs"

# blkid stub: reads "$STUB_DIR/blkid_types" ("<dev> <type>" lines) so runs can
# simulate a vfat ESP (to exercise the fmask/dmask mount path). Empty => no output.
cat > "$STUB_BIN/blkid" <<'BLKID'
#!/usr/bin/env bash
dev=""
for a in "$@"; do case "$a" in /dev/*) dev="$a";; esac; done
if [ -n "$dev" ] && [ -s "$STUB_DIR/blkid_types" ]; then
    awk -v d="$dev" '$1==d{print $2; exit}' "$STUB_DIR/blkid_types"
fi
exit 0
BLKID
chmod +x "$STUB_BIN/blkid"
for c in sync blockdev ping; do
    printf '#!/usr/bin/env bash\nexit 0\n' > "$STUB_BIN/$c"
    chmod +x "$STUB_BIN/$c"
done
printf '#!/usr/bin/env bash\nexit 1\n' > "$STUB_BIN/mountpoint"
chmod +x "$STUB_BIN/mountpoint"

# nixos-version stub (stateVersion detection in gen_base_config)
printf '#!/usr/bin/env bash\necho "26.05"\n' > "$STUB_BIN/nixos-version"
chmod +x "$STUB_BIN/nixos-version"

export PATH="$STUB_BIN:$PATH"
export STUB_DIR
export NIXINSTALL_SKIP_DEV_CHECK=1
export NIXINSTALL_MNT_ROOT="$TEST_DIR/mnt"
MNT="$NIXINSTALL_MNT_ROOT"

: > "$STUB_DIR/sudo.log"

# ──[loud safety banner]
echo "──────────────────────────────────────────────────────────"
echo " TEST MODE: destructive commands are stubbed/no-ops."
echo " sudo deny-list blocks: reboot, poweroff, shutdown, halt,"
echo "   cfdisk, fdisk, sfdisk, parted, dd, rm, mv."
echo " If any BLOCKED command is attempted, the suite FAILS."
echo "──────────────────────────────────────────────────────────"

# ──[load nixinstall (guard prevents main() from running)]
source "$SCRIPT_DIR/nixinstall"

# ═══════════════════════════════════════════════════════════════
echo "== pick_part: parsing (IFS regression) =="
printf 'vda    40G\nvda1   512M\nvda2   39.5G\nvda3   2G\n' > "$STUB_DIR/lsblk_parts"
printf '/dev/vda2 | 39.5G\n' > "$STUB_DIR/choose"
assert_eq "/dev/vda2" "$(pick_part /dev/vda "Root partition" "required" "")" "unformatted 3-col line -> clean /dev/vda2"

printf 'vda    40G\nvda1   512M vfat\nvda2   39.5G linux\n' > "$STUB_DIR/lsblk_parts"
printf '/dev/vda2 | 39.5G | linux\n' > "$STUB_DIR/choose"
assert_eq "/dev/vda2" "$(pick_part /dev/vda "Root partition" "required" "")" "formatted 3-col line (fstype) -> /dev/vda2"

# ═══════════════════════════════════════════════════════════════
echo "== pick_part: chosen-part dedup =="
printf 'vda    40G\nvda1   512M\nvda2   39.5G\n' > "$STUB_DIR/lsblk_parts"
printf '/dev/vda2 | 39.5G\n' > "$STUB_DIR/choose"
pick_part /dev/vda "Root partition" "required" $'/dev/vda1' >/dev/null
if grep -qF '/dev/vda1' "$STUB_DIR/last_options"; then
    fail "chosen /dev/vda1 still offered in dropdown"
else
    pass "chosen /dev/vda1 excluded from dropdown options"
fi

# ═══════════════════════════════════════════════════════════════
echo "== pick_part: manual entry =="
printf 'vda    40G\nvda1   512M\n' > "$STUB_DIR/lsblk_parts"
printf 'Type manually...\n' > "$STUB_DIR/choose"
printf '/dev/vda2\n' > "$STUB_DIR/inputs"
assert_eq "/dev/vda2" "$(pick_part /dev/vda "Root partition" "required" "")" "manual entry /dev/vda2"

# ═══════════════════════════════════════════════════════════════
echo "== pick_part: None (skip) for optional =="
printf 'vda    40G\nvda1   512M\n' > "$STUB_DIR/lsblk_parts"
printf 'None (skip)\n' > "$STUB_DIR/choose"
assert_eq "" "$(pick_part /dev/vda "Swap partition (or skip)" "optional" "")" "None (skip) -> empty"

# ═══════════════════════════════════════════════════════════════
echo "== pick_part: device placeholders =="
printf 'nvme0n1    1T\nnvme0n1p1  512M\n' > "$STUB_DIR/lsblk_parts"
printf 'Type manually...\n' > "$STUB_DIR/choose"
printf '\n' > "$STUB_DIR/inputs"
: > "$STUB_DIR/input_args"
pick_part /dev/nvme0n1 "EFI boot partition" "required" "" >/dev/null
assert_contains "nvme0n1p1" "$STUB_DIR/input_args" "nvme p-suffix placeholder (/dev/nvme0n1p1)"
printf 'vda    40G\nvda1   512M\n' > "$STUB_DIR/lsblk_parts"
printf 'Type manually...\n' > "$STUB_DIR/choose"
printf '\n' > "$STUB_DIR/inputs"
pick_part /dev/vda "EFI boot partition" "required" "" >/dev/null
assert_contains "/dev/vda1" "$STUB_DIR/input_args" "vda placeholder (/dev/vda1)"
printf 'nvme0n1    1T\nnvme0n1p1  512M\n' > "$STUB_DIR/lsblk_parts"
printf 'Type manually...\n' > "$STUB_DIR/choose"
printf '/dev/nvme0n1p1\n' > "$STUB_DIR/inputs"
assert_eq "/dev/nvme0n1p1" "$(pick_part /dev/nvme0n1 "EFI boot partition" "required" "")" "manual nvme entry"

# ═══════════════════════════════════════════════════════════════
echo "== plan_partitions: layout plans =="
expected=$'label|dos\npart|/dev/vda1||L|root'
assert_eq "$expected" "$(plan_partitions /dev/vda BIOS ext4 false false)" "BIOS+ext4 flat: MBR + root takes rest"

expected=$'label|gpt\npart|/dev/vda1|512M|U|boot\npart|/dev/vda2|8G|S|swap\npart|/dev/vda3|12G|L|root\npart|/dev/vda4||L|home'
assert_eq "$expected" "$(plan_partitions /dev/vda UEFI btrfs true true 8G 12G)" "UEFI+btrfs home+swap: ESP, swap, root 12G, home rest"

expected=$'label|dos\npart|/dev/vda1|1G|L|boot-ext4\npart|/dev/vda2|50G|L|root\npart|/dev/vda3||L|home'
assert_eq "$expected" "$(plan_partitions /dev/vda BIOS xfs true false)" "BIOS+xfs home: 1G ext4 /boot, root default 50G, home rest"

expected=$'label|gpt\npart|/dev/vda1|1M|21686148-6449-6E6F-744E-656564454649|biosboot\npart|/dev/vda2||L|root'
assert_eq "$expected" "$(plan_partitions /dev/vda BIOS btrfs false false)" "BIOS+btrfs flat: GPT + 1M BIOS boot (embed area) + root rest"

expected=$'label|gpt\npart|/dev/nvme0n1p1|512M|U|boot\npart|/dev/nvme0n1p2||L|root'
assert_eq "$expected" "$(plan_partitions /dev/nvme0n1 UEFI ext4 false false)" "nvme p-suffix in plan paths"

echo "== plan_partitions: rest-of-disk partition is always LAST =="
rest_last_ok=1
for combo in \
    "BIOS ext4 false false" "UEFI ext4 false false" \
    "UEFI btrfs true true" "BIOS xfs true true" \
    "BIOS btrfs false true" "UEFI xfs true false"; do
    set -- $combo
    last_size=$(plan_partitions /dev/vda "$1" "$2" "$3" "$4" 2G 10G | grep '^part|' | tail -1 | cut -d'|' -f3)
    if [ -n "$last_size" ]; then
        fail "rest partition not last for: $combo (last size='$last_size')"
        rest_last_ok=0
    fi
done
[ "$rest_last_ok" = 1 ] && pass "rest-of-disk partition is last in every combo"

# ═══════════════════════════════════════════════════════════════
echo "== gen_base_config: UEFI + wheel + ssh + key =="
gen_base_config mytzhost "Etc/UTC" myuser '$6$rounds$fakehash' UEFI /dev/vda 1 1 "ssh-ed25519 AAAATESTKEY testcomment" > "$TEST_DIR/cfg_uefi.nix"
assert_contains 'networking.hostName = "mytzhost"' "$TEST_DIR/cfg_uefi.nix" "hostname in config"
assert_contains 'time.timeZone = "Etc/UTC"' "$TEST_DIR/cfg_uefi.nix" "timezone in config"
assert_contains 'boot.loader.systemd-boot.enable = true;' "$TEST_DIR/cfg_uefi.nix" "UEFI -> systemd-boot"
assert_contains 'users.users.myuser = {' "$TEST_DIR/cfg_uefi.nix" "user attrset created"
assert_contains 'extraGroups = [ "wheel" ];' "$TEST_DIR/cfg_uefi.nix" "wheel group set"
assert_contains 'initialHashedPassword = "$6$rounds$fakehash"' "$TEST_DIR/cfg_uefi.nix" "hashed password baked in"
assert_contains 'services.openssh.enable = true;' "$TEST_DIR/cfg_uefi.nix" "ssh enabled"
assert_contains 'ssh-ed25519 AAAATESTKEY' "$TEST_DIR/cfg_uefi.nix" "ssh key authorized"
assert_contains 'experimental-features = [ "nix-command" "flakes" ]' "$TEST_DIR/cfg_uefi.nix" "flakes enabled (nhs works on first boot)"
assert_contains 'networking.networkmanager.enable = true;' "$TEST_DIR/cfg_uefi.nix" "NetworkManager enabled"
assert_contains 'system.stateVersion = "26.05"' "$TEST_DIR/cfg_uefi.nix" "stateVersion detected from nixos-version"

echo "== gen_base_config: BIOS + no wheel + no ssh =="
gen_base_config biohost "Asia/Tokyo" biuser '$6$h2' BIOS /dev/sda 0 0 "" > "$TEST_DIR/cfg_bios.nix"
assert_contains 'boot.loader.grub.device = "/dev/sda";' "$TEST_DIR/cfg_bios.nix" "BIOS -> grub on target disk"
assert_contains 'extraGroups = [ ];' "$TEST_DIR/cfg_bios.nix" "no wheel -> empty groups"
assert_not_contains 'services.openssh' "$TEST_DIR/cfg_bios.nix" "ssh not enabled when declined"

echo "== gen_base_config: parses as Nix =="
if command -v nix-instantiate &>/dev/null; then
    for f in cfg_uefi cfg_bios; do
        if nix-instantiate --parse "$TEST_DIR/$f.nix" >/dev/null 2>&1; then
            pass "$f.nix parses as Nix"
        else
            fail "$f.nix FAILED to parse as Nix"
        fi
    done
else
    echo "  SKIP  nix-instantiate not found"
fi

# ═══════════════════════════════════════════════════════════════
echo "== hash_password: sha512crypt via openssl =="
HASH=$(hash_password testpass123)
case "$HASH" in
    \$6\$*) pass "hash_password returns sha512crypt (\$6\$)" ;;
    *) fail "hash_password returned '$HASH' (expected \$6\$... prefix)" ;;
esac

# ═══════════════════════════════════════════════════════════════
echo "== prompts: validation + retry =="
printf 'BadHost\nmyhost\n' > "$STUB_DIR/inputs"
assert_eq "myhost" "$(prompt_hostname)" "prompt_hostname retries invalid then accepts"

printf 'X\nY\nZ\n' > "$STUB_DIR/inputs"
if out=$(prompt_hostname 2>/dev/null); then
    fail "prompt_hostname should give up after 3 invalid tries"
else
    pass "prompt_hostname gives up after 3 invalid tries (rc=1)"
fi

printf 'BadName\nokuser\n' > "$STUB_DIR/inputs"
assert_eq "okuser" "$(prompt_username)" "prompt_username rejects invalid then accepts"

printf 'root\njar\n' > "$STUB_DIR/inputs"
assert_eq "jar" "$(prompt_username)" "prompt_username rejects reserved name root"

printf 'a\nb\nsecret\nsecret\n' > "$STUB_DIR/inputs"
assert_eq "secret" "$(prompt_password)" "prompt_password retries mismatch then accepts match"

# ═══════════════════════════════════════════════════════════════
echo "== iso_install: full stubbed runs =="

seed_common() {
    printf 'vda 40G disk\n' > "$STUB_DIR/lsblk_disks"
    printf 'vda    40G\nvda1   512M\nvda2   39.5G\nvda3   2G\n' > "$STUB_DIR/lsblk_parts"
    printf 'NAME   SIZE FSTYPE MOUNTPOINT\nvda    40G\nvda1   512M\nvda2   39.5G\nvda3   2G\n' > "$STUB_DIR/lsblk_display"
    printf '/dev/vda | 40G\n' > "$STUB_DIR/fzf"
    : > "$STUB_DIR/nixos_install.log"
    : > "$STUB_DIR/mkfs.log"
    : > "$STUB_DIR/mount.log"
    : > "$STUB_DIR/btrfs.log"
    : > "$STUB_DIR/git.log"
    : > "$STUB_DIR/genconfig.log"
    rm -rf "$MNT"
}

seed_manual() { # boot fs choose_extra confirm_extra input_prefix_url...
    # $1 boot, $2 fs, $3 extra choose lines (already newline-terminated), $4 extra confirm lines
    seed_common
    {
        printf '%s\n' "$1"
        printf '%s\n' "$2"
        printf 'Manual (open cfdisk)\n'
        printf '%b' "$3"
    } > "$STUB_DIR/choose"
    {
        printf '1\n'   # This will ERASE data on $target_disk. Continue? -> yes
        printf '1\n'   # Separate /home partition? -> yes
        printf '0\n'   # Swap partition? -> no
        printf '%b' "$4" # extra confirms (e.g. btrfs subvol) between swap and cfdisk
        printf '0\n'   # Run cfdisk now? -> no
        printf '1\n'   # Ready to continue after partitioning? -> yes
        printf '1\n'   # Format these partitions? -> yes
        printf '1\n'   # Grant sudo (wheel)? -> yes
        printf '0\n'   # Enable SSH? -> no
        printf '1\n'   # Proceed with installation? -> yes
        printf '0\n'   # Drop into installed system shell? -> no
        printf '0\n'   # Unmount and reboot now? -> no
    } > "$STUB_DIR/confirms"
}

# ---- run A: UEFI + ext4 + separate home (manual partitioning)
(
    printf '/dev/vda1 vfat\n' > "$STUB_DIR/blkid_types"   # ESP is vfat -> masks expected
    seed_manual "UEFI" "ext4" \
        $'/dev/vda1 | 512M\n/dev/vda2 | 39.5G\n/dev/vda3 | 2G\n' \
        ""
    printf 'myhost\nEtc/UTC\nmyuser\npass123\npass123\nhttps://github.com/y-jar/nix-config.git\n' > "$STUB_DIR/inputs"
    if out=$(iso_install 2>&1); then rc=0; else rc=$?; fi
    assert_eq "0" "$rc" "iso_install exits 0 (run A: UEFI ext4 home)"
    if [ "$rc" != "0" ]; then printf '%s\n' "--- iso_install output (run A) ---" "$out"; fi
)

CFG="$MNT/etc/nixos/configuration.nix"
assert_contains 'networking.hostName = "myhost"' "$CFG" "run A: hostname written"
assert_contains 'users.users.myuser = {' "$CFG" "run A: user written"
assert_contains 'initialHashedPassword = "$6$' "$CFG" "run A: hashed password written"
assert_contains 'boot.loader.systemd-boot.enable = true;' "$CFG" "run A: systemd-boot (UEFI)"
assert_contains 'experimental-features' "$CFG" "run A: flakes enabled"
assert_not_contains 'services.openssh' "$CFG" "run A: ssh stayed off"
assert_contains '/dev/vda2' "$MNT/etc/nixos/hardware-configuration.nix" "run A: hardware config generated into /etc/nixos"
assert_contains "--root $MNT" "$STUB_DIR/nixos_install.log" "run A: nixos-install --root <mnt>"
assert_contains "--no-root-passwd" "$STUB_DIR/nixos_install.log" "run A: nixos-install --no-root-passwd"
assert_not_contains "--flake" "$STUB_DIR/nixos_install.log" "run A: no --flake (base install, no switch)"
assert_contains "NIX_CONFIG=experimental-features = nix-command flakes" "$STUB_DIR/nixos_install.log" "run A: NIX_CONFIG reaches nixos-install past sudo (env wrapper)"
assert_contains "git clone https://github.com/y-jar/nix-config.git $MNT/home/myuser/nix-config" "$STUB_DIR/git.log" "run A: repo cloned into /home/myuser/nix-config"
if [ -f "$MNT/home/myuser/nix-config/flake.nix" ]; then
    pass "run A: cloned tree exists at /home/myuser/nix-config"
else
    fail "run A: cloned tree missing at /home/myuser/nix-config"
fi
assert_contains "mkfs.fat -F 32 /dev/vda1" "$STUB_DIR/mkfs.log" "run A: EFI formatted fat32"
assert_contains "mkfs.ext4 -F /dev/vda2" "$STUB_DIR/mkfs.log" "run A: root formatted ext4"
assert_contains "mkfs.ext4 -F /dev/vda3" "$STUB_DIR/mkfs.log" "run A: home formatted ext4"
assert_contains "mount /dev/vda2 $MNT" "$STUB_DIR/mount.log" "run A: root mounted at <mnt>"
assert_contains "mount --mkdir /dev/vda3 $MNT/home" "$STUB_DIR/mount.log" "run A: home mounted"
assert_contains "mount --mkdir -o fmask=0077,dmask=0077 /dev/vda1 $MNT/boot" "$STUB_DIR/mount.log" "run A: ESP mounted with fmask/dmask"

# ---- run B: BIOS + xfs + separate home (manual) -> grub + ext4 /boot
(
    : > "$STUB_DIR/blkid_types"   # ext4 /boot is not vfat -> plain mount (no masks)
    printf 'vda    40G\nvda1   1G\nvda2   16G\nvda3   2G\n' > "$STUB_DIR/lsblk_parts"
    printf 'NAME   SIZE FSTYPE MOUNTPOINT\nvda    40G\nvda1   1G\nvda2   16G\nvda3   2G\n' > "$STUB_DIR/lsblk_display"
    seed_manual "BIOS" "xfs" \
        $'/dev/vda2 | 16G\n/dev/vda1 | 1G\n/dev/vda3 | 2G\n' \
        ""
    printf 'bihost\nEtc/UTC\nbiuser\nbipass\nbipass\nhttps://github.com/y-jar/nix-config.git\n' > "$STUB_DIR/inputs"
    if out=$(iso_install 2>&1); then rc=0; else rc=$?; fi
    assert_eq "0" "$rc" "iso_install exits 0 (run B: BIOS xfs home)"
    if [ "$rc" != "0" ]; then printf '%s\n' "--- iso_install output (run B) ---" "$out"; fi
)

assert_contains 'boot.loader.grub.device = "/dev/vda";' "$CFG" "run B: grub on target disk (BIOS)"
assert_contains 'networking.hostName = "bihost"' "$CFG" "run B: hostname written"
assert_contains "mkfs.ext4 -F /dev/vda1" "$STUB_DIR/mkfs.log" "run B: ext4 /boot for XFS GRUB"
assert_contains "mkfs.xfs -f /dev/vda2" "$STUB_DIR/mkfs.log" "run B: root xfs"
assert_contains "mkfs.xfs -f /dev/vda3" "$STUB_DIR/mkfs.log" "run B: home xfs"
assert_not_contains "mkfs.fat" "$STUB_DIR/mkfs.log" "run B: no FAT (not UEFI)"
assert_contains "mount --mkdir /dev/vda1 $MNT/boot" "$STUB_DIR/mount.log" "run B: ext4 /boot mounted"

# ---- run C: UEFI + btrfs + subvolumes (flat home) -> subvol create + mounts
(
    seed_manual "UEFI" "btrfs" \
        $'/dev/vda1 | 512M\n/dev/vda2 | 39.5G\n' \
        $'1\n'
    # flat home: flip the Separate /home confirm from 1 -> 0
    sed -i '2s/.*/0/' "$STUB_DIR/confirms"
    printf 'bthost\nEtc/UTC\nbtuser\nbtpass\nbtpass\nhttps://github.com/y-jar/nix-config.git\n' > "$STUB_DIR/inputs"
    if out=$(iso_install 2>&1); then rc=0; else rc=$?; fi
    assert_eq "0" "$rc" "iso_install exits 0 (run C: UEFI btrfs subvol flat)"
    if [ "$rc" != "0" ]; then printf '%s\n' "--- iso_install output (run C) ---" "$out"; fi
)

assert_contains 'networking.hostName = "bthost"' "$CFG" "run C: hostname written"
assert_contains "mkfs.btrfs -f /dev/vda2" "$STUB_DIR/mkfs.log" "run C: root btrfs"
assert_contains "mkfs.fat -F 32 /dev/vda1" "$STUB_DIR/mkfs.log" "run C: EFI fat32"
assert_contains "subvolume create $MNT/@" "$STUB_DIR/btrfs.log" "run C: @ subvolume created"
assert_contains "subvolume create $MNT/@home" "$STUB_DIR/btrfs.log" "run C: @home subvolume created"
assert_contains "subvolume create $MNT/@nix" "$STUB_DIR/btrfs.log" "run C: @nix subvolume created"
assert_contains "mount -o subvol=@ /dev/vda2 $MNT" "$STUB_DIR/mount.log" "run C: root mounted with subvol=@"
assert_contains "mount --mkdir -o subvol=@home /dev/vda2 $MNT/home" "$STUB_DIR/mount.log" "run C: flat home via subvol=@home"
assert_contains "mount --mkdir -o subvol=@nix /dev/vda2 $MNT/nix" "$STUB_DIR/mount.log" "run C: /nix via subvol=@nix"

# ═══════════════════════════════════════════════════════════════
echo "== iso_install: auto-mode run (env-driven, BIOS ext4 swap+home) =="
(
    seed_common
    export NIXINSTALL_AUTO=1
    export NIXINSTALL_AUTO_DISK=vda
    export NIXINSTALL_AUTO_ERASE=1
    export NIXINSTALL_AUTO_BOOT=BIOS
    export NIXINSTALL_AUTO_FS=ext4
    export NIXINSTALL_AUTO_HOME=1
    export NIXINSTALL_AUTO_SWAP=1
    export NIXINSTALL_AUTO_SWAP_SIZE=2G
    export NIXINSTALL_AUTO_CFDISK=0
    export NIXINSTALL_AUTO_READY=1
    export NIXINSTALL_AUTO_FORMAT=1
    export NIXINSTALL_AUTO_UNMOUNT=1
    export NIXINSTALL_AUTO_NETWORK_CONTINUE=1
    export NIXINSTALL_AUTO_HOSTNAME=autohost
    export NIXINSTALL_AUTO_TIMEZONE=Asia/Tokyo
    export NIXINSTALL_AUTO_USERNAME=autouser
    export NIXINSTALL_AUTO_PASSWORD=autopass
    export NIXINSTALL_AUTO_WHEEL=1
    export NIXINSTALL_AUTO_SSH=1
    export NIXINSTALL_AUTO_SSH_KEY="ssh-ed25519 AAAACATEGORYKEY testkey"
    export NIXINSTALL_AUTO_BOOT_PART=
    export NIXINSTALL_AUTO_ROOT_PART=/dev/vda2
    export NIXINSTALL_AUTO_HOME_PART=/dev/vda3
    export NIXINSTALL_AUTO_SWAP_PART=/dev/vda4
    export NIXINSTALL_AUTO_REPO=https://github.com/y-jar/nix-config.git
    export NIXINSTALL_AUTO_PROCEED=1
    export NIXINSTALL_AUTO_REBOOT=0
    if out=$(iso_install 2>&1); then rc=0; else rc=$?; fi
    assert_eq "0" "$rc" "iso_install exits 0 (run D: auto mode)"
    if [ "$rc" != "0" ]; then printf '%s\n' "--- iso_install output (run D) ---" "$out"; fi
    unset NIXINSTALL_AUTO NIXINSTALL_AUTO_DISK NIXINSTALL_AUTO_ERASE NIXINSTALL_AUTO_BOOT \
          NIXINSTALL_AUTO_FS NIXINSTALL_AUTO_HOME NIXINSTALL_AUTO_SWAP NIXINSTALL_AUTO_SWAP_SIZE \
          NIXINSTALL_AUTO_CFDISK NIXINSTALL_AUTO_READY NIXINSTALL_AUTO_FORMAT NIXINSTALL_AUTO_UNMOUNT \
          NIXINSTALL_AUTO_NETWORK_CONTINUE NIXINSTALL_AUTO_HOSTNAME NIXINSTALL_AUTO_TIMEZONE \
          NIXINSTALL_AUTO_USERNAME NIXINSTALL_AUTO_PASSWORD NIXINSTALL_AUTO_WHEEL NIXINSTALL_AUTO_SSH \
          NIXINSTALL_AUTO_SSH_KEY NIXINSTALL_AUTO_BOOT_PART NIXINSTALL_AUTO_ROOT_PART \
          NIXINSTALL_AUTO_HOME_PART NIXINSTALL_AUTO_SWAP_PART NIXINSTALL_AUTO_REPO \
          NIXINSTALL_AUTO_PROCEED NIXINSTALL_AUTO_REBOOT
)

assert_contains 'networking.hostName = "autohost"' "$CFG" "run D: auto hostname"
assert_contains 'time.timeZone = "Asia/Tokyo"' "$CFG" "run D: auto timezone"
assert_contains 'users.users.autouser = {' "$CFG" "run D: auto username"
assert_contains 'services.openssh.enable = true;' "$CFG" "run D: ssh enabled via env"
assert_contains 'AAAACATEGORYKEY' "$CFG" "run D: ssh key authorized via env"
assert_contains 'boot.loader.grub.device = "/dev/vda";' "$CFG" "run D: BIOS grub"
assert_contains "mkswap /dev/vda4" "$STUB_DIR/mkfs.log" "run D: swap partition mkswap'd"
assert_contains "swapon /dev/vda4" "$STUB_DIR/mount.log" "run D: swap enabled"
assert_contains "--no-root-passwd" "$STUB_DIR/nixos_install.log" "run D: nixos-install ran"
assert_not_contains "--flake" "$STUB_DIR/nixos_install.log" "run D: still no --flake in auto mode"
assert_contains "git clone https://github.com/y-jar/nix-config.git $MNT/home/autouser/nix-config" "$STUB_DIR/git.log" "run D: clone into auto user home"

# ═══════════════════════════════════════════════════════════════
echo "== iso_install: auto-partition flow (TEST_MODE, BIOS gpt btrfs) =="
(
    seed_common
    unset NIXINSTALL_AUTO_BOOT_PART NIXINSTALL_AUTO_ROOT_PART NIXINSTALL_AUTO_HOME_PART NIXINSTALL_AUTO_SWAP_PART || true
    export NIXINSTALL_AUTO=1
    export NIXINSTALL_TEST_MODE=1
    export NIXINSTALL_AUTO_PARTITION=1
    export NIXINSTALL_AUTO_DISK=vda
    export NIXINSTALL_AUTO_ERASE=1
    export NIXINSTALL_AUTO_BOOT=BIOS
    export NIXINSTALL_AUTO_FS=btrfs
    export NIXINSTALL_AUTO_HOME=1
    export NIXINSTALL_AUTO_SWAP=1
    export NIXINSTALL_AUTO_SWAP_SIZE=2G
    export NIXINSTALL_AUTO_SUBVOL=1
    export NIXINSTALL_AUTO_ROOT_SIZE=12G
    export NIXINSTALL_AUTO_FORMAT=1
    export NIXINSTALL_AUTO_HOSTNAME=parthost
    export NIXINSTALL_AUTO_TIMEZONE=Etc/UTC
    export NIXINSTALL_AUTO_USERNAME=partuser
    export NIXINSTALL_AUTO_PASSWORD=partpass
    export NIXINSTALL_AUTO_REPO=
    export NIXINSTALL_AUTO_PROCEED=1
    export NIXINSTALL_AUTO_REBOOT=0
    if out=$(iso_install 2>&1); then rc=0; else rc=$?; fi
    printf '%s' "$out" > "$STUB_DIR/runE.log"
    assert_eq "0" "$rc" "iso_install exits 0 (run E: auto-partition TEST_MODE)"
    unset NIXINSTALL_AUTO NIXINSTALL_TEST_MODE NIXINSTALL_AUTO_PARTITION NIXINSTALL_AUTO_DISK \
          NIXINSTALL_AUTO_ERASE NIXINSTALL_AUTO_BOOT NIXINSTALL_AUTO_FS NIXINSTALL_AUTO_HOME \
          NIXINSTALL_AUTO_SWAP NIXINSTALL_AUTO_SWAP_SIZE NIXINSTALL_AUTO_SUBVOL NIXINSTALL_AUTO_ROOT_SIZE \
          NIXINSTALL_AUTO_HOSTNAME NIXINSTALL_AUTO_TIMEZONE NIXINSTALL_AUTO_USERNAME \
          NIXINSTALL_AUTO_PASSWORD NIXINSTALL_AUTO_REPO NIXINSTALL_AUTO_PROCEED NIXINSTALL_AUTO_REBOOT
)

assert_contains 'auto_partition: gpt layout on /dev/vda' "$STUB_DIR/runE.log" "run E: gpt layout chosen (BIOS+btrfs)"
assert_contains 'bios-boot (GRUB embed area, no fs, not mounted): /dev/vda1' "$STUB_DIR/runE.log" "run E: 1M BIOS boot identified as embed area"
assert_contains 'swap: /dev/vda2' "$STUB_DIR/runE.log" "run E: swap at vda2"
assert_contains 'root: /dev/vda3' "$STUB_DIR/runE.log" "run E: root at vda3"
assert_contains 'home: /dev/vda4' "$STUB_DIR/runE.log" "run E: home (rest) at vda4"
assert_contains 'Layout: boot=none root=/dev/vda3' "$STUB_DIR/runE.log" "run E: BIOS boot part NOT treated as /boot (no mount, no format)"
assert_contains 'Core NixOS installed successfully!' "$STUB_DIR/runE.log" "run E: install reported success"
assert_not_contains 'No home partition in auto layout' "$STUB_DIR/runE.log" "run E: home part wired through (no fallback warn)"

# ═══════════════════════════════════════════════════════════════
echo "== iso_install: nixos-install failure -> friendly error (dead-code bug regression) =="
(
    seed_manual "UEFI" "ext4" \
        $'/dev/vda1 | 512M\n/dev/vda2 | 39.5G\n' \
        ""
    # flat home: flip the Separate /home confirm from 1 -> 0
    sed -i '2s/.*/0/' "$STUB_DIR/confirms"
    printf 'failhost\nEtc/UTC\nfailuser\nfailpass\nfailpass\nhttps://github.com/y-jar/nix-config.git\n' > "$STUB_DIR/inputs"
    export NIXOS_INSTALL_FAIL=1
    if out=$(iso_install 2>&1); then rc=0; else rc=$?; fi
    printf '%s' "$out" > "$STUB_DIR/runF.log"
    assert_eq "1" "$rc" "iso_install returns 1 when nixos-install fails (run F)"
    unset NIXOS_INSTALL_FAIL
)

assert_contains 'Installation failed' "$STUB_DIR/runF.log" "run F: friendly error message shown (not a set -e death)"
assert_contains 're-run Iso Install' "$STUB_DIR/runF.log" "run F: recovery hint shown"
if [ -s "$STUB_DIR/git.log" ]; then
    fail "run F: clone ran after failed install (should abort before Step 11)"
else
    pass "run F: clone never ran after failed install"
fi

# ═══════════════════════════════════════════════════════════════
echo "== nixinstall TEST-MODE guard: run_privileged =="
: > "$STUB_DIR/sudo.log"
NIXINSTALL_TEST_MODE=1 run_privileged reboot poweroff cfdisk
if grep -qF 'BLOCKED:' "$STUB_DIR/sudo.log" 2>/dev/null; then
    fail "run_privileged skipped under TEST_MODE but sudo.log flagged it"
else
    pass "run_privileged is a no-op under NIXINSTALL_TEST_MODE=1"
fi
NIXINSTALL_TEST_MODE=1 run_privileged mkfs.ext4 -F /dev/vda2
if grep -qF 'BLOCKED:' "$STUB_DIR/sudo.log" 2>/dev/null; then
    fail "run_privileged skip wrote to sudo.log"
else
    pass "run_privileged skip never reaches sudo stub"
fi

# ═══════════════════════════════════════════════════════════════
echo "== safety: no dangerous command was attempted =="
if grep -qF 'BLOCKED:' "$STUB_DIR/sudo.log" 2>/dev/null; then
    fail "sudo deny-list triggered:"
    sed 's/^/    /' "$STUB_DIR/sudo.log"
else
    pass "sudo deny-list never triggered"
fi

echo ""
echo "Results: $PASS passed, $FAIL failed"
[ "$FAIL" -eq 0 ] || exit 1
echo "ALL TESTS PASSED"
